version: '3.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3325:3306
    networks:
      - back
  redis:
    image: redis:6
    command: redis-server --requirepass 123
    ports:
      - '6380:6379'

volumes:
  mysql_data:

networks:
  back:

