require('dotenv-safe').config({allowEmptyValues : true});

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const languages = [
    {iso: "aa", "name": "Afar"},
    {iso: "ab", "name": "Abkhazian"},
    {iso: "ae", "name": "Avestan"},
    {iso: "af", "name": "Afrikaans"},
    {iso: "ak", "name": "Akan"},
    {iso: "am", "name": "Amharic"},
    {iso: "an", "name": "Aragonese"},
    {iso: "ar", "name": "Arabic"},
    {iso: "as", "name": "Assamese"},
    {iso: "av", "name": "Avaric"},
    {iso: "ay", "name": "Aymara"},
    {iso: "az", "name": "Azerbaijani"},
    {iso: "ba", "name": "Bashkir"},
    {iso: "be", "name": "Belarusian"},
    {iso: "bg", "name": "Bulgarian"},
    {iso: "bh", "name": "Bihari languages"},
    {iso: "bi", "name": "Bislama"},
    {iso: "bm", "name": "Bambara"},
    {iso: "bn", "name": "Bengali"},
    {iso: "bo", "name": "Tibetan"},
    {iso: "br", "name": "Breton"},
    {iso: "bs", "name": "Bosnian"},
    {iso: "ca", "name": "Catalan"},
    {iso: "ce", "name": "Chechen"},
    {iso: "ch", "name": "Chamorro"},
    {iso: "co", "name": "Corsican"},
    {iso: "cr", "name": "Cree"},
    {iso: "cs", "name": "Czech"},
    {iso: "cu", "name": "Church Slavic"},
    {iso: "cv", "name": "Chuvash"},
    {iso: "cy", "name": "Welsh"},
    {iso: "da", "name": "Danish"},
    {iso: "de", "name": "German"},
    {iso: "dv", "name": "Maldivian"},
    {iso: "dz", "name": "Dzongkha"},
    {iso: "ee", "name": "Ewe"},
    {iso: "el", "name": "Greek"},
    {iso: "en", "name": "English"},
    {iso: "eo", "name": "Esperanto"},
    {iso: "es", "name": "Spanish"},
    {iso: "et", "name": "Estonian"},
    {iso: "eu", "name": "Basque"},
    {iso: "fa", "name": "Persian"},
    {iso: "ff", "name": "Fulah"},
    {iso: "fi", "name": "Finnish"},
    {iso: "fj", "name": "Fijian"},
    {iso: "fo", "name": "Faroese"},
    {iso: "fr", "name": "French"},
    {iso: "fy", "name": "Western Frisian"},
    {iso: "ga", "name": "Irish"},
    {iso: "gd", "name": "Gaelic"},
    {iso: "gl", "name": "Galician"},
    {iso: "gn", "name": "Guarani"},
    {iso: "gu", "name": "Gujarati"},
    {iso: "gv", "name": "Manx"},
    {iso: "ha", "name": "Hausa"},
    {iso: "he", "name": "Hebrew"},
    {iso: "hi", "name": "Hindi"},
    {iso: "ho", "name": "Hiri Motu"},
    {iso: "hr", "name": "Croatian"},
    {iso: "ht", "name": "Haitian"},
    {iso: "hu", "name": "Hungarian"},
    {iso: "hy", "name": "Armenian"},
    {iso: "hz", "name": "Herero"},
    {iso: "ia", "name": "Interlingua"},
    {iso: "id", "name": "Indonesian"},
    {iso: "ie", "name": "Interlingue"},
    {iso: "ig", "name": "Igbo"},
    {iso: "ii", "name": "Sichuan Yi"},
    {iso: "ik", "name": "Inupiaq"},
    {iso: "io", "name": "Ido"},
    {iso: "is", "name": "Icelandic"},
    {iso: "it", "name": "Italian"},
    {iso: "iu", "name": "Inuktitut"},
    {iso: "ja", "name": "Japanese"},
    {iso: "jv", "name": "Javanese"},
    {iso: "ka", "name": "Georgian"},
    {iso: "kg", "name": "Kongo"},
    {iso: "ki", "name": "Kikuyu"},
    {iso: "kj", "name": "Kuanyama"},
    {iso: "kk", "name": "Kazakh"},
    {iso: "kl", "name": "Kalaallisut"},
    {iso: "km", "name": "Central Khmer"},
    {iso: "kn", "name": "Kannada"},
    {iso: "ko", "name": "Korean"},
    {iso: "kr", "name": "Kanuri"},
    {iso: "ks", "name": "Kashmiri"},
    {iso: "ku", "name": "Kurdish"},
    {iso: "kv", "name": "Komi"},
    {iso: "kw", "name": "Cornish"},
    {iso: "ky", "name": "Kirghiz"},
    {iso: "la", "name": "Latin"},
    {iso: "lb", "name": "Luxembourgish"},
    {iso: "lg", "name": "Ganda"},
    {iso: "li", "name": "Limburgan"},
    {iso: "ln", "name": "Lingala"},
    {iso: "lo", "name": "Lao"},
    {iso: "lt", "name": "Lithuanian"},
    {iso: "lu", "name": "Luba-Katanga"},
    {iso: "lv", "name": "Latvian"},
    {iso: "mg", "name": "Malagasy"},
    {iso: "mh", "name": "Marshallese"},
    {iso: "mi", "name": "Maori"},
    {iso: "mk", "name": "Macedonian"},
    {iso: "ml", "name": "Malayalam"},
    {iso: "mn", "name": "Mongolian"},
    {iso: "mr", "name": "Marathi"},
    {iso: "ms", "name": "Malay"},
    {iso: "mt", "name": "Maltese"},
    {iso: "my", "name": "Burmese"},
    {iso: "na", "name": "Nauru"},
    {iso: "nb", "name": "Norwegian"},
    {iso: "nd", "name": "North Ndebele"},
    {iso: "ne", "name": "Nepali"},
    {iso: "ng", "name": "Ndonga"},
    {iso: "nl", "name": "Dutch"},
    {iso: "nn", "name": "Norwegian"},
    {iso: "no", "name": "Norwegian"},
    {iso: "nr", "name": "South Ndebele"},
    {iso: "nv", "name": "Navajo"},
    {iso: "ny", "name": "Chichewa"},
    {iso: "oc", "name": "Occitan"},
    {iso: "oj", "name": "Ojibwa"},
    {iso: "om", "name": "Oromo"},
    {iso: "or", "name": "Oriya"},
    {iso: "os", "name": "Ossetic"},
    {iso: "pa", "name": "Panjabi"},
    {iso: "pi", "name": "Pali"},
    {iso: "pl", "name": "Polish"},
    {iso: "ps", "name": "Pushto"},
    {iso: "pt", "name": "Portuguese"},
    {iso: "qu", "name": "Quechua"},
    {iso: "rm", "name": "Romansh"},
    {iso: "rn", "name": "Rundi"},
    {iso: "ro", "name": "Romanian"},
    {iso: "ru", "name": "Russian"},
    {iso: "rw", "name": "Kinyarwanda"},
    {iso: "sa", "name": "Sanskrit"},
    {iso: "sc", "name": "Sardinian"},
    {iso: "sd", "name": "Sindhi"},
    {iso: "se", "name": "Northern Sami"},
    {iso: "sg", "name": "Sango"},
    {iso: "si", "name": "Sinhala"},
    {iso: "sk", "name": "Slovak"},
    {iso: "sl", "name": "Slovenian"},
    {iso: "sm", "name": "Samoan"},
    {iso: "sn", "name": "Shona"},
    {iso: "so", "name": "Somali"},
    {iso: "sq", "name": "Albanian"},
    {iso: "sr", "name": "Serbian"},
    {iso: "ss", "name": "Swati"},
    {iso: "st", "name": "Sotho, Southern"},
    {iso: "su", "name": "Sundanese"},
    {iso: "sv", "name": "Swedish"},
    {iso: "sw", "name": "Swahili"},
    {iso: "ta", "name": "Tamil"},
    {iso: "te", "name": "Telugu"},
    {iso: "tg", "name": "Tajik"},
    {iso: "th", "name": "Thai"},
    {iso: "ti", "name": "Tigrinya"},
    {iso: "tk", "name": "Turkmen"},
    {iso: "tl", "name": "Tagalog"},
    {iso: "tn", "name": "Tswana"},
    {iso: "to", "name": "Tonga"},
    {iso: "tr", "name": "Turkish"},
    {iso: "ts", "name": "Tsonga"},
    {iso: "tt", "name": "Tatar"},
    {iso: "tw", "name": "Twi"},
    {iso: "ty", "name": "Tahitian"},
    {iso: "ug", "name": "Uighur"},
    {iso: "uk", "name": "Ukrainian"},
    {iso: "ur", "name": "Urdu"},
    {iso: "uz", "name": "Uzbek"},
    {iso: "ve", "name": "Venda"},
    {iso: "vi", "name": "Vietnamese"},
    {iso: "vo", "name": "Volapük"},
    {iso: "wa", "name": "Walloon"},
    {iso: "wo", "name": "Wolof"},
    {iso: "xh", "name": "Xhosa"},
    {iso: "yi", "name": "Yiddish"},
    {iso: "yo", "name": "Yoruba"},
    {iso: "za", "name": "Zhuang"},
    {iso: "zh", "name": "Chinese"},
    {iso: "zu", "name": "Zulu"}
]

const createLanguages = async ()=>{
    languages.map(async(lang) => {
        const language = await prisma.language.create({
            data: lang,
        })
        console.log(language)
    })
}

createLanguages();