const customStatusCodes = {
    OK:                      1,
    VALIDATION_ERROR:       -1,
    FILE_MISSING:           -2,
    S3_ERROR:               -4,
    SOMETHING_WENT_WRONG:   -5,
    EMPTY_TOKEN:            -6,
    UNAUTHORIZED_ACCESS:    -7,
    RELATION_VIOLATION:     -8,
    FILE_TYPE_WRONG:        -9,
    FILE_UPLOAD_ERROR:      -10,
    ICON_NOT_FOUND:         -11,
    FILE_ERROR:             -12,
    TOKEN_EXPIRED:          -13,
    TOKEN_MALFORMED:        -14,
    ACCOUNT_NOT_FOUND:      -15,
    USER_ALREADY_EXISTS:    -16,
    TOKEN_NOT_FOUND:        -17,
    USER_ALREADY_CONFIRMED: -18,
    USER_NOT_FOUND:         -19,
    NO_TOKEN_PROVIDED:      -20,
    USER_NOT_VERIFIED:      -21,
    STATUS_NOT_ALLOWED:     -22,
    DB_ERROR:               -23,
    NOT_ALLOWED:            -24,
    INVALID_TOKEN:          -25,
    USER_EXISTS_BUT_NOT_VERIFIED: -26,
    ACCOUNT_NOT_ENABLED:    -27,
    USER_NOT_ENABLED:       -28,
    BAD_REQUEST:            -29,
    INVALID_PIN:            -30,
    LAST_USER_IN_ACCOUNT:   -31,
    LAST_ADMIN_IN_ACCOUNT:  -32,
    INTERNAL_ERROR:         -33,
    INVALID_TALK_METHOD:    -34,
    ADMIN_USER_ALREADY_EXISTS: -35,
    ADMIN_USERNAME_ALREADY_EXISTS: -36,
    PRODUCT_NOT_FOUND:      -37,
    NOT_FOUND:              -38,
    GPT_FAILED:             -39,
    PROMPT_EXISTS:          -40,
    WAITLIST_EXISTS:        -41,
    TOKEN_ALREADY_REDEEMED: -42,
    DEPRECATED:             -43,
    ACCOUNT_ALREADY_EXISTS: -44,
    TOKEN_IS_NO_LONGER_VALID: -45,
    ALREADY_EXISTS:         -46,
    EXPECTED_FUTURE_DATE:   -47,
    ADMIN_PERMISSION_REQ:   -48,

    INVALID_LANGUAGE:       -1000,

    SUBSCRIPTION_NOT_ACTIVE: -2000,
    NOT_ENOUGH_TOKENS:       -2001,
}

module.exports = customStatusCodes;