# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Eureka CI

on:
  push:
    branches: [ "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: yarn 
    - name: Run test suite
      run: yarn test:simple
    - run: echo "${{ secrets.AWS_EC2_PRODUCTION_HOST }}"
    - name: SSH into AWS EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_PRODUCTION_HOST }}
        username: 'ubuntu'
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/eureka-api
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 18
          yarn
          npx prisma db push
          pm2 reload ecosystem.config.js
    - run: echo "DONE DEPLOYING "